FROM python:3.12.2-bullseye as builder

WORKDIR /usr/src/backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libxml2-dev libxslt-dev netcat -y

RUN pip install --upgrade pip
# RUN pip install flake8==6.0.0
COPY . /usr/src/backend/
# RUN flake8 --ignore=E501,F401 .

COPY ./requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/backend/wheels -r requirements.txt


# Final

FROM python:3.12.2-bullseye

RUN mkdir -p /home/backend

RUN addgroup --system backend && adduser --system --group backend

# create the appropriate directories
ENV HOME=/home/backend
ENV APP_HOME=/home/backend/django
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
WORKDIR $APP_HOME

RUN apt-get update && apt-get install -y --no-install-recommends netcat
COPY --from=builder /usr/src/backend/wheels /wheels
COPY --from=builder /usr/src/backend/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache /wheels/*

# COPY ./entrypoint.sh .
# RUN sed -i 's/\r$//g'  $APP_HOME/entrypoint.sh
# RUN chmod +x  $APP_HOME/entrypoint.sh

COPY . $APP_HOME
RUN mkdir -p /home/backend/nltk_data && chown -R backend:backend /home/backend/nltk_data
RUN chown -R backend:backend $APP_HOME

USER backend

# ENTRYPOINT ["/home/backend/web/entrypoint.sh"]
