# Builder Stage
FROM python:3.12.2-bullseye as builder

WORKDIR /usr/src/backend

RUN pip3 install poetry

COPY pyproject.toml poetry.lock /usr/src/backend/

ENV PATH="${PATH}:/root/.poetry/bin"

RUN poetry install --no-root --no-dev


FROM python:3.12.2-bullseye

RUN mkdir -p /home/backend

RUN addgroup --system backend && adduser --system --group backend

ENV HOME=/home/backend
ENV APP_HOME=/home/backend/django
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
WORKDIR $APP_HOME

RUN apt-get update && apt-get install -y --no-install-recommends netcat

# Copy only dependencies from builder stage
COPY --from=builder /usr/local/lib/python3.12/site-packages/ /usr/local/lib/python3.12/site-packages/
COPY --from=builder /usr/local/bin/poetry /usr/local/bin/poetry

# Copy application code
COPY . $APP_HOME

RUN mkdir -p /home/backend/nltk_data && chown -R backend:backend /home/backend/nltk_data
RUN chown -R backend:backend $APP_HOME

USER backend
