services:

    django:
        container_name: django
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - SummarEase-Backend-Network
        # command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --timeout 1000 --workers=3
        volumes:
            - static_volume:/home/backend/django/staticfiles
            - ./backend/gunicorn_conf.py:/home/backend/django/backend/gunicorn_conf.py:ro
            - ./logs/gunicorn/:/var/log/gunicorn/:rw
        expose:
            - 8000
        env_file:
            - ./.env

    nginx:
        container_name: nginx1
        build: ./nginx
        networks:
            - SummarEase-Backend-Network
        volumes:
            - static_volume:/home/backend/web/staticfiles
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./logs/nginx/:/var/log/nginx/:rw
        ports:
            - 1337:80
        depends_on:
            - django

networks:
    SummarEase-Backend-Network:
        driver: bridge
        external: True

volumes:
    static_volume:
