.PHONY: rs
rs:
	- poetry run python manage.py runserver

.PHONY: mm
mm:
	- poetry run python manage.py makemigrations

.PHONY: mig
mig:
	- poetry run python manage.py migrate

.PHONY: shell
shell:
	- poetry run python manage.py shell

.PHONY: mpyhelp
mpyhelp:
	- poetry run python manage.py --help


.PHONY: offpg
offpg:
	- sudo systemctl stop postgresql




